services:
  log-centralizer:
    build:
      context: ./docker/log-centralizer
      dockerfile: Dockerfile
    container_name: easysave-log-centralizer
    ports:
      - "5080:8080"
    environment:
      - LOGS_DIRECTORY=/data/logs
    volumes:
      - easysave-centralized-logs:/data/logs
    restart: unless-stopped

volumes:
  easysave-centralized-logs:
